### ISSUE TITLE
while creating delta pkg .forceignore not getting copied to working directory

### ISSUE THREAD

**Issue by ramesh-karanji** [Accenture/sfpowerkit#445] opened 2020-10-28 02:02 UTC
Create Delta Package based on two commits task is failing with below error while delta package creation
##[error]ENOENT: no such file or directory, open 'portal_src_delta/.forceignore'

**Comment by manisfdcsfdx** [comment] 2021-01-16 11:06
@azlam-abdulsalam not able to reproduce this one, we are handling project not having forceignore. i have tested in project where forceignore not exist as well. 

keeping this open to see if @ramesh-karanji facing this anymore.

**Comment by azlam-abdulsalam** [comment] 2021-01-24 21:11
Closing this as no further feedback from @ramesh-karanji . Please feel free to reopen of required

**Closed by azlam-abdulsalam** 2021-01-24 21:11 UTC
