### ISSUE TITLE
Profile reconcile targeted to project throw "Cannot read properties of undefined (reading 'getUsername')"

### ISSUE THREAD

**Issue by Lram-11** [Accenture/sfpowerkit#660] opened 2022-03-31 11:20 UTC
running sfdx sfpowerkit:source:profile:reconcile -s
I get this error:

ERROR [2022-03-31 11:08:27.212 +0000] (sfpowerkit): Cannot read properties of undefined (reading 'getUsername')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'getUsername')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'getUsername')
              at ..\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:96:45
              at new Promise (<anonymous>)
              at ProfileReconcile.runWorkers (..\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:77:29)
              at ProfileReconcile.<anonymous> (..\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:64:28)
              at Generator.next (<anonymous>)
              at fulfilled (..\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:24:58)
    }
ERROR [2022-03-31 11:08:27.212 +0000] (sfpowerkit): An error occured during profile reconcile. You can rerun the command after a moment.

It has been weeks since I first got this error, I tried many ways to fix this like updating, uninstalling and re-installing, search through the repository but nothing worked by now.

**To Reproduce**

1. sfdx sfpowerkit:source:profile:reconcile -s

**Desktop (please complete the following information):**

-   OS: Windows
-   Node Version 16.14.0
-   Version of sfpowerkit 4.1.5 feb22
-  sfdx v7.143.0

**Comment by azlam-abdulsalam** [comment] 2022-03-31 11:37
Duplicate of #637

**Closed by azlam-abdulsalam** 2022-03-31 11:37 UTC
Labels: duplicate
