### ISSUE TITLE
Scratch org pool creation goes into infinite loop when DevHub has no active scratch orgs

### ISSUE THREAD

**Issue by ImJohnMDaniel** [Accenture/sfpowerkit#456] opened 2021-01-16 21:51 UTC
**Describe the bug**
Scratch org pool creation goes into infinite loop when DevHub has no active scratch orgs

**To Reproduce**

1. set up sfpowerkit
2. ensure DevHub has no ActiveScratchOrg
3. execute command `sfdx sfpowerkit:pool:create -f scratch-org-pool-config.json -v DevHub`
*****FAILURE POINT
* Monitor ActiveScratchOrgs -- note no new scratch orgs created
* command execution does not conclude and runs until cancelled.

**Expected behavior**
Scratch org pool creation should proceed as expected.

**Desktop (please complete the following information):**

- OS: MacOS v11.1
- Version of sfpowerkit -- v2.5.3 linked to local clone of GIT repo
- Salesforce Org Version -- standard DE Edition Winter 21

**Comment by azlam-abdulsalam** [comment] 2021-01-16 21:53
@ImJohnMDaniel  possible duplicate of this
https://github.com/Accenture/sfpowerkit/issues/454

Working on a hotfix

**Comment by ImJohnMDaniel** [comment] 2021-01-16 21:56
I doubt it.  In my tests, I was never able to get to "Creating Scratch  Org  1 of X.." message.

FYI on the PR with the fix.

**Comment by azlam-abdulsalam** [comment] 2021-01-16 21:57
@manisfdcsfdx  can you incorporate this in the proposed patch?

**Comment by ImJohnMDaniel** [comment] 2021-01-16 22:00
@azlam-abdulsalam -- Applying the fix that I have for this one in my local version allows me to proceed far enough to get to the issue mentioned in #454. 

I can see the scratch orgs being created, but the SFPOWERKIT fields on the ScratchOrgInfo object (i.e. `Allocation_status__c`, `Password__c`, and `Pooltag__c`) are not populated.

**Comment by azlam-abdulsalam** [comment] 2021-01-16 22:03
Yes this command is broken now with issue #454, we are working on a fix. The node wrapper cant find the commands in user namespace as , the cli moved it to its own npm module

#453 is the PR for it

**Comment by azlam-abdulsalam** [comment] 2021-01-17 09:08
@manisfdcsfdx  we might need a hotfix for this, lets reschedule for an early release

**Comment by manisfdcsfdx** [comment] 2021-01-17 21:57
> @manisfdcsfdx we might need a hotfix for this, lets reschedule for an early release

sure once pool:create is fixed lets release both in a hotfix.

**Closed** 2021-01-17 23:23 UTC
Labels: breaking, bug
