### ISSUE TITLE
Option to Skip the Pool Create Pre-Requisite Check

### ISSUE THREAD

**Issue by msimonis** [Accenture/sfpowerkit#531] opened 2021-06-17 16:44 UTC
**Is your feature request related to a problem? Please describe.**
Currently the way the pre-requisite check works for creating pools, is that it uses the metadata API to verify that the ScratchOrgInfo has the Allocation_status__c field. But this requires ModifyAllData or ModifyMetadata permissions for the user running the script, which is not always ideal.

**Describe the solution you'd like**
A way to skip the pre-requisite check when running the pool:create command.

**Describe alternatives you've considered**
I was looking into the permissions required, and for our business, it is unlikely all developers would be granted such permissions.

**Additional context**
I am going to stand up a PR with the new flag and skipping logic.

**Comment by azlam-abdulsalam** [comment] 2021-06-17 23:02
Are you planning to roll this command out per developer? as in each one creates their own pool. We typically use this in a CI/CD pipeline with a service account responsible for creating the pool daily

**Comment by msimonis** [comment] 2021-06-18 12:52
@azlam-abdulsalam not per developer, but a specific few. Maybe not the primary use case, but I have found it nice to do testing of the pool locally before automating it on a CI/CD pipeline. And from what I can tell, the pre-requisite check was the only logic requiring such permissions.

**Comment by yippie** [comment] 2022-02-24 19:33
Please add this. This check is the only reason the CI user even needs these permissions and is an utterly worthless check. Doing a query for the field and getting an error accomplishes the exact same thing without the highly elevated permission.

Also, we would like our CI user to be able to use the free DX Only licenses instead of paying for a dedicated license. Due to this check, we can't do that.

**Comment by azlam-abdulsalam** [comment] 2022-02-26 00:21
Duplicate of #642

**Closed by azlam-abdulsalam** 2022-02-26 00:21 UTC
Labels: analysis
