### ISSUE TITLE
Possible issue with org shape compatibility

### ISSUE THREAD

**Issue by LawrenceLoz** [Accenture/sfpowerkit#486] opened 2021-03-03 08:57 UTC
**Describe the bug**
Using the command "sfdx sfpowerkit:pool:create -f scratchorg-poolconfig.json -v MyDevHub" with a scratchorg-poolconfig.json which references a project-scratch-def.json with an org shape ("sourceOrg") attribute for our production org leads to "Unable to provision scratch org" errors in output

**To Reproduce**
Create scratch org shape, and a project-scratch-def.json referencing the id of this shape as below:
```
{
  "orgName": "Demo company",
  "features": [],
  "sourceOrg": "00D4J000000Fh0SUAS",
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "securitySettings": {
      "passwordPolicies": {
        "enableSetPasswordInApi": true
      }
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    }
  }
}
```

scratchorg-poolconfig.json file:
```
{
    "pool": {
        "expiry": 2,
        "tag":"Dev_pool",
        "max_allocation": 2,
        "config_file_path": "config/project-scratch-def.json",
        "relax_all_ip_ranges": true
    }
}
```

Run command below:
`sfdx sfpowerkit:pool:create -f scratchorg-poolconfig.json -v MyDevHub`

**Expected behavior**
Scratch orgs set up as per definition files

**Screenshots**
![image](https://user-images.githubusercontent.com/32834730/109779044-1f4bb480-7c38-11eb-9fe0-77c59c1872ee.png)

**Desktop (please complete the following information):**

- OS: Issue seen on Ubuntu running on Github Actions and Windows OS
- Node Version: v12.18.3
- Version of sfpowerkit[e.g 1.45.0]
- Salesforce Org Version: Unlimited

**Additional context**
Changing the project-scratch-def.json to the one below (removed "sourceOrg" and added "edition") and rerunning the same command results in successfully created scratch orgs:

```
{
  "orgName": "Demo company",
  "features": [],
  "edition": "Developer",
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "securitySettings": {
      "passwordPolicies": {
        "enableSetPasswordInApi": true
      }
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    }
  }
}

```

**Comment by manisfdcsfdx** [comment] 2021-03-03 23:45
@LawrenceLoz can you confirm few things 

1. build runs in which user context
2. the build user has access to the shape org?
3. can you just run `sfdx force:org:create -f scratchorg-poolconfig.json -v MyDevHub` in your pipeline to see if the scratch org is getting created using shape. 

this will help us to narrow down the issue. @azlam-abdulsalam

**Comment by LawrenceLoz** [comment] 2021-03-04 09:08
Hi @manisfdcsfdx 

Thanks for looking into this.

I've seen the same issue for two users, one of which is our deployment (CI) user. This user has minimal permissions required for deployment and does have access to the org the shape was taken from (the Dev Hub)

The issue also happens for my personal account, which is on the standard system admin profile in the Dev Hub and I originally generated the org shape with this user.

I presume you mean check I can run the command `sfdx force:org:create -f config\project-scratch-def.json -v MyDevHub`. I can confirm this successfully creates a scratch org with shape configuration matching production. (running your command gives "No such column 'Pool' on sobject of type ScratchOrgInfo" error but I guess you didn't intend this)

Thanks
Lawrence

**Comment by azlam-abdulsalam** [comment] 2021-03-04 09:45
@LawrenceLoz  is this particular devhub have all the prerequisite fields (for pools) deployed?  This is an interesting one!

**Comment by LawrenceLoz** [comment] 2021-03-04 10:13
@azlam-abdulsalam yes pretty sure it does - I deployed these fairly recently.

Also worth mentioning the DevHub and project-scratch-def.json are the same ones I've been using with sfpowerscripts:orchestrator:prepare and have seen this successfully create a scratch org with the org shape.

**Comment by azlam-abdulsalam** [comment] 2021-03-04 11:15
Aha, then it should be easy to fix, something with script execution then..

**Comment by azlam-abdulsalam** [comment] 2021-03-05 00:37
@LawrenceLoz  I am unable to reproduce this issue, I have pushed a branch which doesn't suppress the error logs, so we can see what is going on. The branch is chore/inspect_shape

Can you clone this repo and do the following in the particular directory
1. npm i
2. sfdx plugins:link
3. create a pool and then drop me the logs

**Comment by LawrenceLoz** [comment] 2021-03-05 07:52
Thanks Azlam, output attached for a run using version in the branch with and without the org shape being used in project-scratch-def.json. Looks like there may be some pointers there:
[createWithOrgShape.log](https://github.com/Accenture/sfpowerkit/files/6088914/createWithOrgShape.log)
[createWithoutOrgShape.log](https://github.com/Accenture/sfpowerkit/files/6088915/createWithoutOrgShape.log)

Let me know if there's anything else you'd like me to try

**Comment by azlam-abdulsalam** [comment] 2021-03-05 10:20
@LawrenceLoz  something  in your production settings is getting carried into the scratch org, which is preventing a password to be generated.

Can you try creating a password using 
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_passwd.htm

And let us know

@manisfdcsfdx

**Comment by LawrenceLoz** [comment] 2021-03-05 10:59
Yes you're right @azlam-abdulsalam - getting the message below setting a password

```
ERROR running force:user:password:generate:  INSUFFICIENT_ACCESS: Cannot set password for self
Try this:
Create a scratch org with the enableSetPasswordInApi org security setting set to TRUE and try again.

```

(setting password is fine in a scratch org without a shape)

enableSetPasswordInApi deprecated in v51.0 and I can't think which setting in the UI might affect this in the shape... In any case though not an issue with sfpowerkit (a clearer warning without logs would be helpful but a nice to have) - happy for you to close the issue if you think no action needed

Thanks a lot for your help!

**Comment by azlam-abdulsalam** [comment] 2021-03-05 13:02
I will create a PR for fixing the error log.

Thanks for your support.

**Comment by LawrenceLoz** [comment] 2021-03-06 04:59
Hi @azlam-abdulsalam looking into this a bit more I don't think there's an easy workaround and this is something which will likely affect others as well.

The reason I was struggling to find a setting in the UI is that this relates to a permission "Allow use of setPassword() API for self-resets" which is no longer available once it's been deactivated in the org. Here are before/after screenshots of me disabling this in a blank scratch org:

![Disabling permission](https://user-images.githubusercontent.com/32834730/110194942-e72db700-7e6d-11eb-9f6f-6fefd6fd64aa.PNG)

![image](https://user-images.githubusercontent.com/32834730/110194932-d2e9ba00-7e6d-11eb-9894-dcf3f0b347d5.png)

The second screenshot is how the settings in our production org look - no option to re-enable.

The official docs indicate this is expected: https://dreamevent.secure.force.com/articleView?id=admin_password.htm&type=0

I've confirmed I'm able to reset a password for the primary scratch org user in a scratch org with the permission enabled, but get an error trying to do the same thing in a blank scratch org with the permission unchecked:
![image](https://user-images.githubusercontent.com/32834730/110195386-56f07180-7e6f-11eb-8bb1-fdfc71087ee1.png)

Until recently I believe the enableSetPasswordInApi flag in project-scratch-def.json would have overridden this (toggle to v50.0 of this help page https://developer.salesforce.com/docs/atlas.en-us.228.0.api_meta.meta/api_meta/meta_securitysettings.htm), but this is now deprecated (I actually had the setting set to true when creating the examples above).

Do you think there's a way around this in the way sfpowerkit handles users and password setting?

One potential option - if a new admin user is created using force:user:create and "generatePassword": true in a user-def.json this username and password can be issued. This might need to be done on sfpowerkit fetch rather than create so the email can be set to the correct developer's email - when I tried this I needed to verify identity through a code sent to the user's email

**Comment by LawrenceLoz** [comment] 2021-03-06 06:20
Sorry please ignore my last message - just documentation explaining the override has been moved from a setting to a feature (https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md)

Using `"features": ["EnableSetPasswordInApi"]` in my project-scratch-def.json this is now working. Thanks again for your help @azlam-abdulsalam and @manisfdcsfdx

**Comment by manisfdcsfdx** [comment] 2021-03-08 03:04
@LawrenceLoz so are you able to create scratch org with and without shape and password is set for both scratch org as well.

I will add `"features": ["EnableSetPasswordInApi"]` in recommendations in order to create with password or else i will add a warning password cannot be set for the scratch org, use JWT auth flow to access the scratch org.

@azlam-abdulsalam FYI

**Comment by manisfdcsfdx** [comment] 2021-03-08 07:54
@LawrenceLoz I have added the error handling and necessary warning can you try v2.8.1 using `sfdx plugins:install sfpowerkit@2.8.1` let us know if works for you.

**Comment by LawrenceLoz** [comment] 2021-03-09 05:29
Thanks @manisfdcsfdx, this looks good. Without EnableSetPasswordInApi I can see the raw Salesforce error and the sfpowerkit message indicating the failing step. Also checked this still works successfully when permission is set.

Good to see there's a more helpful error message in the new version of the CLI too: https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md

**Comment by manisfdcsfdx** [comment] 2021-03-09 23:12
Thanks @LawrenceLoz glad this helps, closing the issue now. Feel free to raise any issue and reach out in case of any assistance required.

**Closed by manisfdcsfdx** 2021-03-09 23:12 UTC
Labels: enhancement, investigating
