### ISSUE TITLE
Error During Profile Reconcile - TypeError: items.find is not a function

### ISSUE THREAD

**Issue by vuha-acn** [Accenture/sfpowerkit#537] opened 2021-06-22 23:09 UTC
**Describe the bug**
Retrieved and attempted to reconcile profile and received the error message - TypeError: items.find is not a function

**To Reproduce**

1. sfdx sfpowerkit:source:profile:retrieve -n "Profile 1" -u OrgAlias
2. sfdx sfpowerkit:source:profile:reconcile -u OrgAlias -f access-mgmt/main/default/profiles -n "Profile 1" 

**Expected behavior**
Reconcile profile against destination org and in a deployable state.

**Screenshots**
Error Message -

INFO [2021-06-22 22:57:28.448 +0000] (sfpowerkit): Reconciling profile /Users/user.name/Repository/repo/access-mgmt/main/default/profiles/Profile Name.profile-meta.xml
ERROR [2021-06-22 22:58:35.989 +0000] (sfpowerkit): items.find is not a function
    TypeError: items.find is not a function
        at MetadataRetriever.<anonymous> (/Users/user.name/.local/share/sfdx/node_modules/sfpowerkit/lib/impl/metadata/retriever/metadataRetriever.js:129:35)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/user.name/.local/share/sfdx/node_modules/sfpowerkit/lib/impl/metadata/retriever/metadataRetriever.js:24:58)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR [2021-06-22 22:58:35.993 +0000] (sfpowerkit): An error occured during profile reconcile. You can rerun the command after a moment.

**Desktop (please complete the following information):**

- OS: MacOX
- Node Version: v16.1.0
- Version of sfpowerkit[e.g 1.45.0] - Latest w/ sfdx-cli/7.105.0 darwin-x64 node-v14.17.0
- Salesforce Org Version [ In case of pre release window ] - Summer '21

**Additional context**

Recent error that didn't exist before.  Potential causes new permissions that are now added for particular Profile related to Summer '21

**Comment by azlam-abdulsalam** [comment] 2021-06-23 00:41
Duplicate of #524 . This is currently fixed in Beta and will be available as part of July Release

**Closed by azlam-abdulsalam** 2021-06-23 00:41 UTC
