### ISSUE TITLE
"sfpowerkit:project:diff" command fails to generate the delta on modified profiles

### ISSUE THREAD

**Issue by artnbondarenko** [Accenture/sfpowerkit#504] opened 2021-04-19 15:37 UTC
**Description:**
When executing the sfdx sfpowerkit:project:diff command on modified profile getting error "Non-whitespace before first tag." 

**To Reproduce:**
1. Modify profile and commit changes.
2. sfdx sfpowerkit:project:diff --revisionfrom abc --output delta --loglevel DEBUG

**Desktop:**
- OS: RedHat 7.9
- Node Version: 12.18.3
- Version of sfpowerkit: 2.8.7

**Additional context**
Full log output: 
sfdx sfpowerkit:project:diff --revisionfrom abc --output delta --loglevel DEBUG

INFO [2021-04-19 15:13:06.227 +0000] (sfpowerkit): Fetching file list from target revision HEAD
DEBUG [2021-04-19 15:13:06.521 +0000] (sfpowerkit): Files to be copied
DEBUG [2021-04-19 15:13:06.521 +0000] (sfpowerkit):
    0: {
      "revisionFrom": "c1e75b3..",
      "revisionTo": "0238466..",
      "path": "force-app\\main\\default\\profiles\\Admin.profile-meta.xml"
    }
INFO [2021-04-19 15:13:18.130 +0000] (sfpowerkit): Generating output summary
INFO [2021-04-19 15:13:18.134 +0000] (sfpowerkit): Copying file .forceignore from git to delta
INFO [2021-04-19 15:13:18.302 +0000] (sfpowerkit): Copying file sfdx-project.json from git to delta
ERRORS
Path                                                    Error Message
──────────────────────────────────────────────────────  ────────────────────────────────
force-app\main\default\profiles\Admin.profile-meta.xml  Non-whitespace before first tag.	
                                                        Line: 0
                                                        Column: 1
                                                        Char: c
ERROR running sfpowerkit:project:diff:  Error parsing diff.

**Comment by genoud** [comment] 2021-04-20 21:29
@artnbondarenko Have you modified the profile manually?
This issue seems to be link to a bug in xml2js.
https://github.com/Leonidas-from-XIV/node-xml2js/issues/345
https://github.com/Leonidas-from-XIV/node-xml2js/issues/390

**Comment by genoud** [comment] 2021-04-23 14:20
Hi @artnbondarenko ,

We use `git show ` to retrieve file content from git. So if you profile in the revision **abc** is a valid xml, this issue should not happen.

Thanks

**Comment by artnbondarenko** [comment] 2021-04-23 14:27
> Hi @artnbondarenko ,
> 
> We use `git show ` to retrieve file content from git. So if you profile in the revision **abc** is a valid xml, this issue should not happen.
> 
> Thanks

That's the point. xml is valid. I tried to format using ways above what you provided and also checked via hex editor. Could you please just to test it on your end?

**Comment by genoud** [comment] 2021-04-27 02:40
@artnbondarenko I was not able to reproduce this. Tested on Mac and Windows. Not able to test on RedHat.

**Comment by azlam-abdulsalam** [comment] 2021-05-25 23:04
@genoud  can we close this, if there is no further progress on this one?

**Comment by genoud** [comment] 2021-05-25 23:07
Yes we can close it.

**Closed** 2021-05-26 07:28 UTC
Labels: investigating
