### ISSUE TITLE
sfpowerkit:project:diff not creating metadata files

### ISSUE THREAD

**Issue by bfalter** [Accenture/sfpowerkit#95] opened 2019-09-16 18:39 UTC
from within a sfdx project, I am running the command
`$ sfdx sfpowerkit:project:diff -d ../temp  -r HEAD~1`

This is generating the expected folder structure of the diffs, but is not actually creating the metadata file. The last folder (in this case, /classes) is empty.

Running the command with --json generates
```
{
  "status": 0,
  "result": []
}
```

sfpowerkit 1.19.1-1
MacOS 10.14.6

**Comment by genoud** [comment] 2019-09-16 19:25
Hello @bfalter ,
Thank you for raising the issue. Can you check if the output of the git diff command return some metadata? Run `git diff --raw  HEAD~1`.

**Comment by bfalter** [comment] 2019-09-16 19:27
Output of `git diff --raw HEAD~1`:

`salesforce/force-app/main/default/classes/AccountService.cls`

This matches the folder structure created by the sfpowerkit command

**Comment by genoud** [comment] 2019-09-16 19:48
I'm getting this error on windows when I run the command with a parent folder as output.
ERROR running sfpowerkit:project:diff:  path should be a `path.relative()`d string, but got "..\test\force-app\main\default\lwc\bikeCard\bikeCard.js-meta.xml"

Can you try with the -d parameter pointing on a folder located in the project directory?

**Comment by bfalter** [comment] 2019-09-16 19:55
with -d pointing at a folder within the project, the same behavior occurs. it creates the folder path but ends in an empty folder. --json output is also the same.

**Comment by genoud** [comment] 2019-09-16 20:49
Are you running the command from the root of the project folder?

**Comment by bfalter** [comment] 2019-09-16 20:56
@genoud yes, I'm running the command from the root of the project folder. If I navigate up 1 level I get the error `This command is required to run from within an SFDX project.`.

(thank you for all of your quick responses today, btw!)

**Comment by swood09** [comment] 2019-09-17 19:28
@genoud is your previous comment suggesting that we should run this command always from a specific directory? So far we have tried in the main project folder, the parent, and a child, and always get the same result: the "new" project directory and subdirectories are created that match the diff, but no files are copied.

**Comment by genoud** [comment] 2019-09-17 19:46
The command should be run from the repository root, as the file path of a git diff command is always relative the the repository root.
That said, I could not reproduce this issue so far. May be it is relate to mac. I don't have a mac to test on it.

**Comment by azlam-abdulsalam** [comment] 2019-09-17 19:54
@manisfdcsfdx  Please have a look at this issue on Mac

**Comment by swood09** [comment] 2019-09-24 18:30
@manisfdcsfdx any update on this issue?

**Comment by azlam-abdulsalam** [comment] 2019-09-24 21:02
We are yet to reproduce this issue, however we have couple of fixes in 1.20.X , Can you update to the latest version and let us know

**Comment by bfalter** [comment] 2019-09-25 19:07
@azlam-abdulsalam I've updated sfpowerkit to sfpowerkit 1.20.1-2

I'm now receiving the following error message when running:
```
MissingBundleError: Missing bundle sfpowerkit:project_diff for locale en_US.
    at Function.loadMessages (~/.local/share/sfdx/node_modules/@salesforce/core/lib/messages.js:243:15)
    at Object.<anonymous> (~/.local/share/sfdx/node_modules/sfpowerkit/lib/impl/project/diff/diffImpl.js:29:42)
    at Module._compile (~/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Function._load (~/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
    at require (~/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
```

**Comment by genoud** [comment] 2019-09-25 19:47
@bfalter this bug was fixed in 1.20.2. Either install it from npm or checkout the release branch.
Pushing a PR to fix it on master.

**Comment by azlamsalam** [comment] 2019-09-26 23:35
@bfalter, all good ? can we close this?

**Comment by bfalter** [comment] 2019-09-27 20:39
@azlam-abdulsalam unfortunately no. I installed 1.20.2 via npm and linked to sfdx. Running the command has a different behavior now. The command no longer creates the file structure. it creates the top-level output directory but without the file structure. json output is still empty. Running git diff confirms the existence of diffs.

**Comment by azlam-abdulsalam** [comment] 2019-09-30 12:40
@bfalter Can you explicitly pass the commit id's for parameters -r and -t, we are able to reproduce this one on mac

**Comment by swood09** [comment] 2019-09-30 14:26
@azlam-abdulsalam we're seeing the same results when passing commit hashes for each parameter. Would it help if we did a video conference / screen share to demonstrate the behavior? I'd be happy to flex to your schedule if it helps us resolve the issue (if you can't tell, we're very eager to be able to use this command in our workflow).

**Comment by azlam-abdulsalam** [comment] 2019-09-30 14:36
that would be awesome, we were planning on a special debug build for you.. @genoud  let me know when we should get this done

**Comment by azlam-abdulsalam** [comment] 2019-10-03 14:35
Apologies for the delay, we will be sending you instructions for the debug build shortly

**Comment by swood09** [comment] 2019-10-03 20:43
Thanks, @azlam-abdulsalam 
@bfalter will be traveling for a few weeks, so I will be the one helping debug. Looking forward to hearing from you!

**Comment by azlam-abdulsalam** [comment] 2019-10-04 06:06
@swood09  can you do the following in the root of the project directory
1. sfdx plugins:install sfpowerkit@alpha
2. sfdx sfpowerkit:project:diff -r <commitfrom> -t <committo> -d <destination> >> output.txt
3. git diff --raw commitfrom committo >> gitoutput.txt

Please send both the output files to @azlam-abdulsalam

**Comment by swood09** [comment] 2019-10-22 16:49
Any progress? We've tried running the command with multiple log options selected, but no difference in output. We've also tried with absolute paths, relative paths, commit shorthand, direct commits (and upgraded to latest version of git, just to be sure). We're still just seeing the top-level directory created, but not sub-dirs and no files copied. CC @josephcarmello

**Comment by azlam-abdulsalam** [comment] 2019-10-23 10:06
I am awaiting feedback from internal folks who uses Mac in the test conditions. Is this happening in any other OS as well?

**Comment by azlam-abdulsalam** [comment] 2019-10-24 20:05
@swood09  We are unable to reproduce this? Can you try a different machine ?

**Comment by azlam-abdulsalam** [comment] 2019-11-04 05:40
@swood09  @bfalter  We have changed the inner working of this command to fix some other issues. Could you test the latest alpha build by using the command 
sfdx plugins:install sfpowerkit@alpha and  let me know if the issue persists

**Comment by swood09** [comment] 2019-11-04 18:51
I see new info on the command line, but did not see expected behavior.


--
Stephen Wood

**Comment by azlam-abdulsalam** [comment] 2019-11-18 13:11
closing this as we are not able to reproduce this one.

**Closed by azlam-abdulsalam** 2019-11-18 13:11 UTC
Labels: bug
