### ISSUE TITLE
sfpowerkit:source:profile:reconcile removes a valid recordtype layout

### ISSUE THREAD

**Issue by MarcDBehr** [Accenture/sfpowerkit#669] opened 2022-04-28 19:30 UTC
**Describe the bug**
When running sfpowerkit:source:profile:reconcile, a specific recordtype layout assignment keeps getting pulled from the profile despite the layout and record type being in the org.

In my profile, I have a page layout assignment for a record type:

![image](https://user-images.githubusercontent.com/3748097/165830620-1f448468-4a4a-44eb-8425-ca9d1f971f73.png)

In the org, the layout exists:

![image](https://user-images.githubusercontent.com/3748097/165829111-155bc24f-06ec-414d-8d15-91cb98a20379.png)

as well as the record type (found with SOQL `SELECT Name, DeveloperName,  SobjectType FROM RecordType where SobjectType = 'Campaign'`:

![image](https://user-images.githubusercontent.com/3748097/165829229-a4f02742-899a-44fd-8078-0d4980736204.png)

Running the reconcile command with trace, I see:

`Found in Org? Campaign.AC_Campaign false`

**To Reproduce**

1. sfdx sfpowerkit:source:profile:reconcile -n Admin -u [org]
2. Look at what was removed from the profile

**Expected behavior**
The record type page layout assignment should not be removed from the profile

**Screenshots**
See above

**Desktop (please complete the following information):**

-   OS: MacBook 12.3.1
-   Node Version: v16.13.2
-   Version of sfpowerkit[e.g 1.45.0]: 4.2.5
-   Salesforce Org Version [ In case of pre release window ] Winter'22 (54.0)

**Additional context**
1. Any/all profiles with the same layouts assignments are removed.
2. If I put the layout assignment back into the profile, it deploys without any errors and the assignment is visible in the org.

**Comment by Caitlyn-Mills** [comment] 2022-04-28 23:29
Thanks for raising the issue @MarcDBehr. We will start looking into this. 

Have you successfully used the reconcile command with a different version of powerkit before?

**Comment by MarcDBehr** [comment] 2022-04-29 09:54
@Caitlyn-Mills This is a new record type and layout, so I can't say that it worked previously. There are other record type layout assignments in the same profiles and they are working fine from what I see.

**Comment by sumanthreddybolledla** [comment] 2022-04-29 16:47
I'm able to reproduce this issue on v4.2.5., Also, I compared the reconcile results between 4.0.3 and 4.2.5 for same Org and Profile, I found the below differences:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/19957368/165988127-ecf276ce-38f4-437d-ac98-b59377e71df8.png">

**Comment by Caitlyn-Mills** [comment] 2022-05-02 03:52
Please test if the same issue occurs on version 4.2.6

**Comment by MarcDBehr** [comment] 2022-05-02 11:26
@Caitlyn-Mills Couple of questions:

1. The PR only appears to update the version number. Am I not seeing the other changes?
2. I don't remember how to test the patch release (it has been a bit since I last did that). Can you remind me how to do this?

**Comment by sumanthreddybolledla** [comment] 2022-05-02 17:39
> Please test if the same issue occurs on version 4.2.6

I have tested this in 4.2.6 and still able to reproduce the issue.

**Comment by Caitlyn-Mills** [comment] 2022-05-04 23:41
> @Caitlyn-Mills Couple of questions:
> 
> 1. The PR only appears to update the version number. Am I not seeing the other changes?
> 2. I don't remember how to test the patch release (it has been a bit since I last did that). Can you remind me how to do this?

Hey @MarcDBehr, There were some changes merged without updating the patch version, so I was unclear if your issue was due to something that was in the code prior to this code being merged. To test the patch release you just have to update the version of sfpowerkit through the cli. 

I am still doing some testing on this issue, it seems there must be some very specific conditions to be able to replicate. 

Thanks for the patience. Hopefully we resolve this one shortly.

**Comment by azlam-abdulsalam** [comment] 2022-05-15 11:28
@sumanthreddybolledla  Can  you test the behaviour in 4.2.7

**Comment by sumanthreddybolledla** [comment] 2022-05-16 14:30
Hi @azlam-abdulsalam , I have tested this in 4.2.7, it is working fine now. I checked both retrieve and reconcile, both have the tags which were missing in previous version..

**Closed** 2022-05-16 22:09 UTC
Labels: bug, in test
