### ISSUE TITLE
sfpowerkit:source:profile:retrieve/reconcile - Duplicate layoutAssignments during extraction of "Admin" Profile

### ISSUE THREAD

**Issue by crazynammer** [Accenture/sfpowerkit#448] opened 2020-12-17 22:42 UTC
**Describe the bug**
Profile Retrieve/Reconcile of  new "Admin" profile from org generate a duplicate layoutAssignments entry causing validation error to destination org.  

**To Reproduce**

1. sfdx sfpowerkit:source:profile:retrieve -n "Admin" -u orgAlias
2. sfdx sfpowerkit:source:profile:reconcile -u orgAlias -f access-mgmt/main/default/profiles -n "Admin"

**Expected behavior**
Clean Profile to validate deploy to next org.

**Screenshots**

![image](https://user-images.githubusercontent.com/7194981/102552420-0b9ba380-4076-11eb-80e5-75ee51e62f18.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Node Version - Latest
- Version of sfpowerkit[e.g 1.45.0] - Latest
- Salesforce Org Version [ In case of pre release window ] - 50.0

**Additional context**

**Comment by genoud** [comment] 2020-12-22 20:22
@crazynammer I was not able to reproduce this. The retrieve and the reconcile does not add items in the profile configuration.

**Comment by crazynammer** [comment] 2020-12-22 20:43
@genoud - Have you enabled Person Account Org in your sandbox and/or scratch org to try to replicate the error. My use case is that the sandbox is enabled with Person Account, each time I pull a full profile down, it does a duplicate of the following block of xml thinking that its needed for both Person and Standard Account.

```
    <layoutAssignments>
        <layout>PersonAccount-Layout Name</layout>
        <recordType>PersonAccount.PersonAccount</recordType>
    </layoutAssignments> 
```

**Comment by genoud** [comment] 2020-12-22 20:47
Yes, I'm testing on an org with person account enabled.

**Comment by crazynammer** [comment] 2020-12-23 00:54
@genoud - For your testing, have you also created a custom Page Layout and do the assignment of that to the System Admin profile and do a full retrieve? I think that would be the best way to reproduce the error because that is my current scenario now.

**Comment by crazynammer** [comment] 2020-12-23 23:43
@genoud - I've done some more tests and here are the results

1. Pull full profile from different org, UAT, and it did not duplicate the tag for layoutAssignment -- PASS
2. Update the PersonAccount in Dev and re-assign the same layout and made changes to the page layout and tried to pull down code again -- FAIL

It seems to be just isolated to this DEV Sandbox so I can pinpoint where the configuration options are.  Let me know if you have any other test cases you want me to perform else we can probably close this ticket and see if it comes up again in different scenario.

**Comment by azlam-abdulsalam** [comment] 2021-02-21 21:16
@crazynammer  Can you confirm this is fixed in the latest alpha version.

**Closed** 2021-03-01 06:28 UTC
Labels: bug
