### ISSUE TITLE
Scratch Org Pool creation failure 

### ISSUE THREAD

**Issue by Caitlyn-Mills** [Accenture/sfpowerkit#454] opened 2021-01-15 02:55 UTC
**Describe the bug**
Unable to provision a scratch org using sfpowerkit:pool:create 

**To Reproduce**

1. npx sfdx sfpowerkit:pool:create

**Expected behavior**
Expected scratch orgs to be created and provisioned. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63215232/104675189-e6fa2080-5734-11eb-8f3a-78c9243d43f1.png)

**Desktop (please complete the following information):**
Pool: Azure Pipelines
Image: ubuntu-20.04

**Comment by azlam-abdulsalam** [comment] 2021-01-15 02:58
Thanks @Caitlyn-Mills  for raising the issue. Its caused by sfdx plugins missing the user namespace.

We are tracking this closely.

**Comment by azlam-abdulsalam** [comment] 2021-01-15 21:02
A fix has been applied and testing out

**Comment by ImJohnMDaniel** [comment] 2021-01-16 22:07
@azlam-abdulsalam -- If you don't mind, would you point me to the active branch that has the hotfix for this issue.  I already have the project setup locally and could verify the fix.  My teams are evaluating Scratch Org Pooling.  We would like to evaluate this weekend as we have some high priority projects that need something like this immediately.  At the moment, the evaluation is blocked by this issue.  Switching to the active hotfix branch would allow us to continue to evaluate while giving your team an independent verification method.  Just let me know.  I appreciate it!

**Comment by azlam-abdulsalam** [comment] 2021-01-16 22:12
Awesome, happy to help, dm me directly for anything you need to make ot work :)

https://github.com/Accenture/sfpowerkit/tree/hotfix/pool

If you are looking at the CI side of stuff, have a look at sfpowerscripts orchestrator as well.

https://dxatscale.gitbook.io/sfpowerscripts/faq/orchestrator
https://github.com/Accenture/sfpowerscripts

**Closed** 2021-01-17 23:23 UTC
Labels: breaking, bug
