### ISSUE TITLE
ERROR running sfpowerkit:project:diff:  Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by sfdcale** [Accenture/sfpowerkit#91] opened 2019-09-15 15:09 UTC
when using the command `sfdx sfpowerkit:project:diff --revisionfrom=HEAD --revisionto=HEAD~10 -d test` if **revisionto** points to a merge commit, it is failing with below error:

> ERROR running sfpowerkit:project:diff:  Cannot read property 'push' of undefined

**Comment by azlam-abdulsalam** [comment] 2019-09-15 21:40
Thanks for raising the issue, We have identified the root cause and will be releasing a patch shortly

**Comment by azlam-abdulsalam** [comment] 2019-09-16 05:37
Fixed in 1.18.4

**Closed by azlam-abdulsalam** 2019-09-16 05:37 UTC
