### ISSUE TITLE
sfdx sfpowerkit:source:profile:reconcile -s are removing Activity profile permission like Task.CustomField__c and Event.CustomField__c which should not be removed

### ISSUE THREAD

**Issue by WellWisherCoder** [Accenture/sfpowerkit#349] opened 2020-08-06 20:22 UTC
**Describe the bug**

**To Reproduce**

1. sfdx sfpowerkit:<module>:<command> <options>

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows/Linux]
- Node Version
- Version of sfpowerkit[e.g 1.45.0]
- Salesforce Org Version [ In case of pre release window ]

**Additional context**

**Comment by genoud** [comment] 2020-08-08 15:23
Cannot reproduce this. Sfpowerkit do keep Task and events Fields and recordTypes.
@WellWisherCoder  could provide more info on this bug?

**Comment by manisfdcsfdx** [comment] 2020-08-30 12:46
@WellWisherCoder can you provide more info.. we cannot reproduce this issue.

**Comment by manisfdcsfdx** [comment] 2020-09-01 07:16
@WellWisherCoder closing this issue as this is not reproduced from our side. Feel free to open this when you more  details on this.

**Closed by manisfdcsfdx** 2020-09-01 07:16 UTC
