### ISSUE TITLE
sfdx sfpowerkit:org:orgcoverage --> Cannot read property 'Name' of null

### ISSUE THREAD

**Issue by JeroenSfdc** [Accenture/sfpowerkit#391] opened 2020-09-17 13:46 UTC
**Describe the bug**
`sfdx sfpowerkit:org:orgcoverage -u imcd--uat -d "/Users/jburgers/Downloads" -f csv`

`Successfully Retrieved the Apex Test Coverage of the org 00D1w0000000c0aEAA`
`coverage:11`
`ERROR running sfpowerkit:org:orgcoverage:  Cannot read property 'Name' of null`
**To Reproduce**
`sfdx sfpowerkit:org:orgcoverage -u imcd--uat -d "/Users/jburgers/Downloads" -f csv`

**Expected behavior**
No error

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: OSX
- Node Version: v14.8.0
- Version of sfpowerkit 2.1.5
- Salesforce Org Version: 

**Additional context**
n/a

**Comment by manisfdcsfdx** [comment] 2020-09-18 01:19
@JeroenSfdc  can you run the command with --json and provide the screenshot, as we are not able to reproduce the issue.

`sfdx sfpowerkit:org:orgcoverage -u imcd--uat -d "/Users/jburgers/Downloads" -f csv --json`

**Comment by azlam-abdulsalam** [comment] 2020-09-18 02:04
@JeroenSfdc  I have a feeling this is related the alias of the org imcd--uat and is somehow getting broken.

**Comment by JeroenSfdc** [comment] 2020-09-18 06:19
`{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read property 'Name' of null",
  "exitCode": 1,
  "commandName": "OrgCoverage",
  "stack": "TypeError: Cannot read property 'Name' of null\n    at /Users/jburgers/.local/share/sfdx/node_modules/sfpowerkit/lib/commands/sfpowerkit/org/orgcoverage.js:94:86\n    at Array.forEach (<anonymous>)\n    at OrgCoverage.getApexCoverageByDetails (/Users/jburgers/.local/share/sfdx/node_modules/sfpowerkit/lib/commands/sfpowerkit/org/orgcoverage.js:81:33)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async OrgCoverage.run (/Users/jburgers/.local/share/sfdx/node_modules/sfpowerkit/lib/commands/sfpowerkit/org/orgcoverage.js:58:35)\n    at async OrgCoverage._run (/Users/jburgers/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:93:40)\n    at async Config.runCommand (/Users/jburgers/.nvm/versions/node/v14.8.0/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/Users/jburgers/.nvm/versions/node/v14.8.0/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/Users/jburgers/.nvm/versions/node/v14.8.0/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\nOuter stack:\n    at Function.wrap (/Users/jburgers/.local/share/sfdx/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at OrgCoverage.catch (/Users/jburgers/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:259:67)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async OrgCoverage._run (/Users/jburgers/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)\n    at async Config.runCommand (/Users/jburgers/.nvm/versions/node/v14.8.0/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/Users/jburgers/.nvm/versions/node/v14.8.0/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/Users/jburgers/.nvm/versions/node/v14.8.0/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/jburgers/.nvm/versions/node/v14.8.0/lib/node_modules/sfdx-cli/dist/cli.js:32:20)",
  "warnings": []
}`

**Comment by azlam-abdulsalam** [comment] 2020-09-18 11:05
Thanks @JeroenSfdc  we are looking into it

**Comment by manisfdcsfdx** [comment] 2020-09-19 02:06
@JeroenSfdc we have applied a hotfix. Can you install version 2.1.6. Let us know if face any issues.

`$ sfdx plugins:install sfpowerkit@2.1.6`

**Comment by manisfdcsfdx** [comment] 2020-09-22 01:23
@JeroenSfdc closing the issue as the bug fix is applied in latest tag. feel free to reopen the issue incase if you get any troubles.

**Closed by manisfdcsfdx** 2020-09-22 01:23 UTC
Labels: hotfix
