### ISSUE TITLE
Plugin install error

### ISSUE THREAD

**Issue by achimraible** [Accenture/sfpowerkit#431] opened 2020-11-25 14:14 UTC
Hi,

with the latest version of SFDX from https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz we get the following error when installing your plugin by using the command 'sfdx plugins:install sfpowerkit'.

[1/4] Resolving packages...Installing plugin sfpowerkit... 
[2/4] Fetching packages...Installing plugin sfpowerkit... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfpowerkit... !
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1

Is this a bug in the plugin, because installing the plugins sfdx-git-packager and sfdx-essentials works fine with the SF CLI version

- OS: Linux
- Node Version 14.15.1
- Version of sfpowerkit latest

Regards
Achim

**Comment by johnforeland** [comment] 2020-11-25 14:35
Same issue. Works fine locally, not on GitHub Actions using ubuntu-latest.

**Comment by WellWisherCoder** [comment] 2020-11-26 16:54
facing same issue

**Comment by azlam-abdulsalam** [comment] 2020-11-26 20:55
We are looking into it, can any one of you provide a screenshot of the error?
Is it only happening in Github actions ?

**Comment by azlam-abdulsalam** [comment] 2020-11-27 06:51
I am still unable to find what is causing the issue, could be us missing yarn and npm together. The following instructions work in Github actions

    // Install SFDX CLI
      - name: Install SFDX CLI
        run: |
             sudo yarn global add sfdx-cli@latest

      - name: Install sfpowerkit
        run: |
              echo 'y' | sfdx plugins:install sfpowerkit@alpha

**Comment by azlam-abdulsalam** [comment] 2020-12-01 03:33
Found out the root cause of this issue, this happened due to the recent update of antlr to 4.9.0 which requires node 14. This dependency is used by salesforce-alm, which we dependent on for Pooling Commands. The current work around is to  update the node engine to use 14.
https://github.com/forcedotcom/cli/issues/746

**Comment by achimraible** [comment] 2020-12-01 08:14
I add this to workaround to our Dockerimage we are using for Git Lab pipeline, but still get the installation error mentioned above we I use the latest version of sfpowerkit.

Installation of version sfpowerkit@2.0.1 is successfull but when I call the command "sfdx git:package -s ${sourceBranch} -t ${targetBranch} -d ${tmp.deployment.folder}/diff -f" I get the following error

[sf:deploy] Finished request 0Af1q00000gJnYdCAK successfully.
     [exec]     Error: Package subpath './v4' is not defined by "exports" in 
     [exec]     /node_modules/uuid/package.json
     [exec]     Code: ERR_PACKAGE_PATH_NOT_EXPORTED
BUILD FAILED

I already install this uuid version to the Docker image

RUN npm install uuidv4

**Comment by azlam-abdulsalam** [comment] 2020-12-01 09:15
@achimraible  that doesn't look like a sfpowerkit command. Its a different plugin.

sfpowerkit git diff functionality is available in the following commmand

https://github.com/Accenture/sfpowerkit#sfpowerkitprojectdiff

**Comment by achimraible** [comment] 2020-12-01 09:32
> @achimraible that doesn't look like a sfpowerkit command. Its a different plugin.
> 
> sfpowerkit git diff functionality is available in the following commmand
> 
> https://github.com/Accenture/sfpowerkit#sfpowerkitprojectdiff

You're right. sorry for that.

**Comment by WellWisherCoder** [comment] 2020-12-01 18:12
So, when can we expect this to work as previously?

**Comment by WellWisherCoder** [comment] 2020-12-01 18:12
I'm currently using the older version - Installation of version sfpowerkit@2.0.1

**Comment by azlam-abdulsalam** [comment] 2020-12-01 22:28
@WellWisherCoder  unless salesforce cli team or antlr decides to fix, we are in a pickle. The current option is to use node14 as the runtime

**Comment by azlam-abdulsalam** [comment] 2020-12-01 22:30
Seems like cli is releasing a patch, and this should go away

**Comment by achimraible** [comment] 2020-12-03 07:59
In order I can't get the plugin up and running again with whatever salesforcdx version I'm using, I created in my deployment script the same functionality you are using. Furthermore to prevent future malfunction when again a SF CLI update breaks the plugin functionality and our CI/CD process is broken caused by this
Thanks for your help in all the issues I created, but from my point of view it is not further work needed from your side

**Comment by azlam-abdulsalam** [comment] 2020-12-03 08:10
@achimraible  it is better to have a docker image, so you have control over the depenendencies

**Comment by achimraible** [comment] 2020-12-03 08:13
I 

> @achimraible it is better to have a docker image, so you have control over the depenendencies

We have a docker image in use which includes the official salesforce sfdx docker image too, but still I can't get it up and running

**Comment by azlam-abdulsalam** [comment] 2020-12-03 08:52
Cool, cli patch will be released tonight as they have closed the issue

**Comment by manisfdcsfdx** [comment] 2020-12-07 02:06
CLI team has applied a patch to remove antlr4 dependency. we have updated to latest cli dependency as well.

**Closed by manisfdcsfdx** 2020-12-07 02:06 UTC
Labels: bug, hotfix
